# Generated by Django 5.0.4 on 2024-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='nika.ip'),
        ),
    ]
