# Generated by Django 5.0.4 on 2024-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0002_ip_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
