# Generated by Django 5.0.4 on 2024-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0004_remove_ip_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='article_views', to='nika.ip'),
        ),
    ]
