# Generated by Django 5.0.4 on 2024-05-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0005_article_view_count_alter_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
