# Generated by Django 5.0.4 on 2024-05-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0006_remove_article_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
