# Generated by Django 5.0.4 on 2024-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0009_alter_article_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubdate',
            field=models.DateTimeField(),
        ),
    ]
