# Generated by Django 5.0.4 on 2024-05-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0013_alter_article_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
